plugins {
   id 'java'
   id 'war'
   id "org.gretty" version "3.1.1" 
}


group = 'br.com.gw'
version = '1.0'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'


repositories {
   mavenCentral()
   maven { url "https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/" }
}


dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:4.0.1' 

    implementation 'org.postgresql:postgresql:42.7.2'
    implementation 'net.sf.jasperreports:jasperreports:6.20.6'
    implementation 'org.apache.commons:commons-dbcp2:2.9.0'
    implementation 'javax.servlet:jstl:1.2'
}


gretty {
   servletContainer = 'tomcat9' 
   contextPath = '/SISTEMA-FRETES' 
}
